# teamspeak服务器地址
host: 127.0.0.1
# query—api账号，该账号需要有ts的serveradmin权限
account: serveradmin
# 密码
password: 123456
# 监听忽略的机器人名称
ignoreBotName: serveradmin
# 监听事件
listenEvent:
  # 用户进入
  clientJoin:
    # 是否开启
    enable: true
    # 事件通知群组列表，多个用逗号隔开
    noticeGroups: 879593407,823931891
    # 事件通知人员列表，多个用逗号隔开
    noticeFriends: 1025744898
    # 根据属性名替换，字段名称被${}包裹，客户端相关信息为${client.XXX},事件相关信息为${event.XXX}，不建议随意修改，字段名称可根据触发相应事件时打印的日志取
    noticeTemplate: 「${client.CLIENT_NICKNAME}」进入了TS，并高呼：“英雄集结！”
  # 用户离开
  clientLeave:
    enable: true
    noticeGroups: 879593407,823931891
    noticeFriends: 1025744898
    noticeTemplate: 「${client.CLIENT_NICKNAME}」因为「${event.reasonmsg}」离开了TS，并大喊：“下播！”
